project/urls.py
#######
#
# Copyright (C) 2011 Phoenorama.org All Rights Reserved.
# Author: Philippe Blondin <pblondin@phoenorama.org>>
#
# This file is part of the Phoenorama program.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#
#######

from django.conf.urls.defaults import patterns, url
from project.views import view_projects, configure_project, add_project, view_results, view_single_result, launch_project, add_schedule, project_wizard
from project.forms import ProjectFormWizard, ProjectForm1, ProjectForm2, ProjectForm3, ProjectForm4

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('project.views',
                       
    url(r'^$', view_projects, name='view_project'),
    url(r'^wizard/$', project_wizard, name='project_wizard'),
    url(r'^create/$', ProjectFormWizard([ProjectForm1, ProjectForm2, ProjectForm3, ProjectForm4]), name='create'),
    url(r'^add/$', add_project, name='add_project'),
    url(r'^add/schedule/$', add_schedule, name='add_schedule'),
    url(r'^configure/(\d+)$', configure_project, name='configure_project'),
    url(r'^launch/(\d+)$', launch_project, name='launch_project'),   
    url(r'^result/(\d+)$', view_results, name='view_results'),
    url(r'^result/(\d+)/(\d+)$', view_single_result, name='view_single_result'),
)

urls.py
#######
#
# Copyright (C) 2011 Phoenorama.org All Rights Reserved.
# Author: Philippe Blondin <pblondin@phoenorama.org>>
#
# This file is part of the Phoenorama program.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#
#######

from django.conf.urls.defaults import patterns, include
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^Phoenorama_FE/', include('Phoenorama_FE.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
    # URL pattern for Django-Sentry
    (r'^sentry/', include('sentry.urls')),

    # Include URL pattern for the Management apps
    (r'^', include('management.urls')),
    
    # Include URL pattern for the Account apps
    #(r'^', include('account.urls')),
    
    # Registration
    (r'^account/', include('account.urls')),
    (r'^account/', include('registration.urls')),

    
    # Include URL pattern for the Project apps
    (r'^project/', include('project.urls')),
    

)


if settings.DEBUG:
    urlpatterns += patterns('',
        # Include Static Media Files
        (r'^css/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT + "/css/"}),
        (r'^img/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT + "/img/"}),
        (r'^js/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT + "/js/"}),
    )

project/models.py
#######
#
# Copyright (C) 2011 Phoenorama.org All Rights Reserved.
# Author: Philippe Blondin <pblondin@phoenorama.org>>
#
# This file is part of the Phoenorama program.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#
#######

from django.db import models
from django.contrib.auth.models import User
from infosec.models import CVE, BUGTRAQ, NVT

##############################
## PROJECT
##############################
class ProjectManager(models.Manager):
    def fromCreator(self, creator):
        self.get_query_set().filter(creator=creator)

class Project(models.Model):
    creator = models.ForeignKey(User, unique=False)   
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)    
    create_time = models.DateTimeField(auto_now_add=True)
    target = models.IPAddressField()
    schedule = models.ForeignKey('Schedule')
    
    # Subscribe the ProjectManager    
    objects = ProjectManager()
       
    class Meta:
        db_table = u'project'
        
    def __unicode__(self):
        return u'%s , %s' % (self.name, self.description)
    
##############################
## SCHEDULE 
##############################
class Schedule(models.Model):
    FREQUENCY_CHOICES = (
        (u'd', u'Daily'),
        (u'w', u'Weekly'),
        (u'm', u'Monthly'),
    )
    
    name = models.CharField(max_length=50)
    comment = models.TextField(null=True, blank=True)
    first_time = models.DateTimeField()
    frequency = models.CharField(max_length=1, choices=FREQUENCY_CHOICES)
    last_time = models.DateTimeField()
    
    class Meta:
        db_table = u'schedule'
        
    def __unicode__(self):
        return str(self.name)

##############################
## PROFILE 
##############################    
class Profile(models.Model):
    name = models.CharField(max_length=50)
    task_templates = models.ManyToManyField('TaskTemplate')
    comment = models.TextField()
    
    class Meta:
        db_table = u'profile'
        
    def __unicode__(self):
        return u"Profile: id [%s], Name [%s], Comment [%s]" % (str(self.id), self.name, self.comment)

##############################
## TASK_TEMPLATE MODEL 
##############################
class TaskTemplate(models.Model):
    name = models.CharField(max_length=50)
    tool = models.ForeignKey('Tool')
    config = models.ForeignKey('Config')
    
    class Meta:
        db_table = u'task_template'
        
    def __unicode__(self):
        return u"Task: id [%s], Name [%s], Tool_id [%s], Config_id [%s]" % (str(self.id), self.name, str(self.tool.id), str(self.config.id))

##############################
## TASK 
##############################
class Task(models.Model):
    STATE_CHOICES = (
        (u'c', u'Created'),
        (u'a', u'Attribute'),
        (u's', u'Started'),
        (u'p', u'Paused'),
        (u'e', u'Ended'),
    )
    
    #target = models.ForeignKey('Target')
    result = models.ForeignKey('Result')
    create_time = models.DateTimeField(auto_now_add=True)
    scan_time = models.DateTimeField()
    state = models.CharField(max_length=1, choices=STATE_CHOICES)
    version_ruleset = models.CharField(max_length=20)
    version_tool = models.CharField(max_length=20)
    
    class Meta:
        db_table = u'task'
        
    def __unicode__(self):
        return u"Execution_task: id [%s], Target_id [%s], Task_id [%s]" % (str(self.id), str(self.target.id), str(self.task.id))
    
##############################
## TOOL 
##############################  
class Tool(models.Model):
    name = models.CharField(max_length=50)
    
    class Meta:
        db_table = u'tool'
        
    def __unicode__(self):
        return u"Tool: id [%s]" % (str(self.id))

##############################
## CONFIG
##############################  
class Config(models.Model):
    name = models.CharField(max_length=50)
    
    class Meta:
        db_table = u'config'
        
    def __unicode__(self):
        return u"Config: id [%s]" % (str(self.id))
    

##############################
## OPENVAS_TASK
##############################
class OpenVASTask(models.Model):
    STATE_CHOICES = (
        (u'c', u'Created'),
        (u'a', u'Attribute'),
        (u's', u'Started'),
        (u'p', u'Paused'),
        (u'e', u'Ended'),
        (u'x', u'Error'),
    )
    project = models.ForeignKey('Project')
    state = models.CharField(max_length=1, choices=STATE_CHOICES, default='c')
    nbeFile = models.FilePathField(path="./resources/results/", match="^project_*", default="")
    targetFile = models.FilePathField(path="./resources/results/", match="^target_*", default="")
    results = models.ManyToManyField('Result', null=True, blank=True, symmetrical=False)
    
    def __unicode__(self):
        return u"Task for project [%s]" % (str(self.project.id))    

##############################
## RESULT
##############################  
class Result(models.Model):
    RISK_FACTOR = (
        (u'c', u'Critical'),
        (u'h', u'High'),
        (u'm', u'Medium'),
        (u'l', u'Low'),
        (u'i', u'Informative'),
        (u'u', u'Unknown'),
        (u'f', u'False positive'),
    )
    
    title = models.CharField(max_length=150, default='')
    summary = models.CharField(max_length=200, default='')
    target = models.CharField(max_length=50, default='')
    description = models.TextField(null=True, blank=True)
    service = models.CharField(max_length=50, null=True, blank=True)
    nvt = models.ForeignKey(NVT, null=True, blank=True)
    cve = models.ForeignKey(CVE, null=True, blank=True)
    bid = models.ForeignKey(BUGTRAQ, null=True, blank=True)
    risk_factor = models.CharField(max_length=1, choices=RISK_FACTOR, default='u')
    
    class Meta:
        db_table = u'result'
        
    def __unicode__(self):
        return u"Result: id [%s]" % (str(self.id))


project/views.py
#######
#
# Copyright (C) 2011 Phoenorama.org All Rights Reserved.
# Author: Philippe Blondin <pblondin@phoenorama.org>>
#
# This file is part of the Phoenorama program.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#
#######

from datetime import date
import time
from django.shortcuts import render_to_response, get_object_or_404, get_list_or_404, Http404
from django.template.context import RequestContext

from management.views import handlePopAdd
from project.tools.openvas import Openvas
from project.forms import ProjectForm, ScheduleForm
from project.models import Project, OpenVASTask


def project_wizard(request):
    return render_to_response('project/project_wizard.html', RequestContext(request, locals()))

def view_projects(request):
    '''
    View projects of the current user.
    '''
    projects = get_list_or_404(Project, creator=request.user)
    return render_to_response('project/view_projects.html', RequestContext(request, locals()))

def add_project(request):
    '''
    Create a new project for the current user.
    '''
    if request.method == 'POST': 
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.creator = request.user
            project.save()
            return render_to_response('account/my_account.html', RequestContext(request, locals()))
    else:
        form = ProjectForm()
    return render_to_response('project/add_project.html', RequestContext(request, locals()))

def add_schedule(request):
    '''
    Create a new schedule for the current user.
    '''
    if '_popup' in request.GET and request.GET['_popup'] == '1':
        return handlePopAdd(request, ScheduleForm, 'schedule') 
    if request.method == 'POST': 
        form = ScheduleForm(request.POST)
        if form.is_valid():
            form.save()
            return render_to_response('account/my_account.html', RequestContext(request, locals()))
    else:
        form = ScheduleForm()
    return render_to_response('project/add_schedule.html', RequestContext(request, locals()))

def view_results(request, project_id):
    '''
    View the results of a project.
    '''
    if request.method == 'GET':
        my_project = get_object_or_404(Project, pk=project_id)
        result_list = get_list_or_404(OpenVASTask, project=my_project)
        return render_to_response('project/view_results.html', RequestContext(request, locals()))
    return render_to_response('account/my_account.html', RequestContext(request, locals()))

def view_single_result(request, project_id, result_id):
    '''
    View a single result.
    '''
    if request.method == 'GET':
        my_project = get_object_or_404(Project, pk=project_id)
        my_task = get_object_or_404(OpenVASTask, pk=result_id)
        if my_task.state == 'e': # Task has finished
            finish = True
            try:
                results = my_task.results.all()
            except IOError:
                raise Http404
        else:
            finish = False
        return render_to_response('project/view_single_result.html', RequestContext(request, locals()))
    return render_to_response('account/my_account.html', RequestContext(request, locals()))
        
def configure_project(request):
    '''
    Configure the project of a user.
    '''
    pass

def launch_project(request, project_id):
    '''
    Launch a project. (i.e start the scan)
    '''  
    if request.method == 'GET':    
        my_project = get_object_or_404(Project, pk=project_id)        
        task = OpenVASTask(project=my_project, state='c', 
                               nbeFile='project_id_%s_%s_%s.nbe' % (str(my_project.id), date.today(), time.time()),
                               targetFile='target_project_id_%s.txt' %(str(my_project.id)))
        task.save()

        o = Openvas(task.id)
        o.configure(targetFile=task.targetFile, nbeFile=task.nbeFile)
        o.start()
            
    return render_to_response('project/launch_project.html', RequestContext(request, locals()))











templates/project/add_project.html
{% extends "base.html" %}
{% block content %}
<script type="text/javascript" src="/media/js/admin/RelatedObjectLookups.js"></script> 
<script language="JavaScript">
	jQuery(document).ready(function(){
		$("#create-project-button").button();
	});
</script>
<h2>Add project</h2>
<table>
<form method="post" action="">
	{% csrf_token %}
	{% include "form/form-error.html" %}
	{% for field in form %}
	<tr>
		<td>{{ field.label_tag }}</td>
		<td>{{ field }}</td>
		{% include "form/field-error.html" %}
	</tr>	
	{% endfor %}
	<tr>
		<td>
			<input id="create-project-button" type="submit" value="Save" />
		</td>
	</tr>
</form>
</table>
{% endblock %}

templates/project/add_schedule.html
{% extends "base.html" %}
{% block content %}
<script language="JavaScript">
	jQuery(document).ready(function(){
		$("#create-schedule-button").button();
		$("#id_first_time, #id_last_time").datepicker({
			minDate: 0,
		});
	});
</script>
<h2>Add schedule</h2>
<table>
<form method="post" action="">
	{% csrf_token %}
	{% include "form/form-error.html" %}
	{% for field in form %}
	<tr>
		<td>{{ field.label_tag }}</td>
		<td>{{ field }}</td>
		{% include "form/field-error.html" %}
	</tr>	
	{% endfor %}
	<tr>
		<td>
			<input id="create-schedule-button" type="submit" value="Save" />
		</td>
	</tr>
</form>
</table>
{% endblock %}

templates/project/launch_project.html
{% extends "base.html" %}
{% block content %}
<script language="JavaScript">
	jQuery(document).ready(function(){
		$( "#progressbar" ).progressbar({
			value: 80
		});
	});
</script>
<style>
	.ui-progressbar-value { background-image: url(/img/style/pbar-ani.gif); }
</style>
<div id="scan result">
	<h3>Launch project: {{ my_project.name|capfirst }}</h3>
	Target: {{ my_project.target }} <br />
	Config: {{ o.config }} <br />
	<hr/><br />
	Scan is now running! Soon you'll be able to get the results <a href="/project/result/{{ my_project.id }}">here</a>.
	<style>
		.ui-progressbar-value { background-image: url(/img/style/pbar-ani.gif); }
	</style>
	<div id="progressbar" style="margin-right: 90%;"></div>
</div>
{% endblock %}

templates/project/project_wizard.html
{% extends "base.html" %}
{% block content %}
<script language="JavaScript">
	jQuery(document).ready(function(){
		$( "#tabs" ).tabs({
			//disabled: [ 1, 2, 3],
			ajaxOptions: {
				error: function( xhr, status, index, anchor ) {
					$( anchor.hash ).html( "Couldn't load this tab. We'll try to fix this as soon as possible. " );
				}
			}
		});
		$("#tos-accept-button, #tos-not-accept-button").button();
	});
</script>

<div id="tabs">
	<ul>
		<li><a href="#tabs-1">Step 1</a></li>
		<li><a href="#tabs-2">Step 2</a></li>
		<li><a href="#tabs-3">Step 3</a></li>
		<li><a href="#tabs-4">Step 4</a></li>
	</ul>
	<div id="tabs-1">
		<p>{% include "management/tos.html" %}</p>
		<table>
		<form method="post" action=".">
			{% csrf_token %}
			{% include "form/form-error.html" %}
			<tr>
				<td>
					<b>*  </b>{{ form.agreement }}<b>I have read and accepted the Service User Agreement.</b>
					{% if form.agreement.errors %}
					<td>
					    <div style="padding: 0pt 0.7em;" class="ui-state-error ui-corner-all">
					        <span style="float: left; margin-right: 0.3em;" class="ui-icon ui-icon-alert"></span>
					        {{ form.agreement.errors|striptags }}
					    </div>
					</td>
					{% endif %}
				</td>
			</tr>
			<tr>
				<td>
					<br />
					<input id="tos-accept-button" type="submit" value="I Agree" />
					<input id="tos-not-accept-button" type="submit" value="Do Not Accept" />
					<input type="hidden" name="{{ step_field }}" value="{{ step0 }}" />
				</td>
			</tr>
		</form>
		</table>
		
	</div>
	<div id="tabs-2"></div>
	<div id="tabs-3"></div>
	<div id="tabs-4"></div>
</div>
{% endblock %}

templates/project/project_wizard_1.html
{% extends "base.html" %}
{% block content %}
<script language="JavaScript">
	jQuery(document).ready(function(){
		$( "#tabs" ).tabs({
			//disabled: [ 1, 2, 3],
			selected: 1,
			ajaxOptions: {
				error: function( xhr, status, index, anchor ) {
					$( anchor.hash ).html( "Couldn't load this tab. We'll try to fix this as soon as possible. " );
				}
			}
		});
		$("#submit-button,").button();
	});
</script>

<div id="tabs">
	<ul>
		<li><a href="#tabs-1">Step 1</a></li>
		<li><a href="#tabs-2">Step 2</a></li>
		<li><a href="#tabs-3">Step 3</a></li>
		<li><a href="#tabs-4">Step 4</a></li>
	</ul>
	<div id="tabs-1"></div>
	<div id="tabs-2">
		<table>
		<form method="post" action=".">
			{% csrf_token %}
			{% include "form/form-error.html" %}
			{% for field in form %}
			<tr>
				<td>{{ field.label_tag }}</td>
				<td>{{ field }}</td>
				{% include "form/field-error.html" %}
			</tr>
			{% endfor %}
			<tr>
				<td>
					<input id="submit-button" type="submit" value="Save" />
					<input type="hidden" name="{{ step_field }}" value="{{ step1 }}" />
				</td>
			</tr>
		</form>
		</table>
		
	</div>
	<div id="tabs-3"></div>
	<div id="tabs-4"></div>
</div>
{% endblock %}

templates/project/view_projects.html
{% extends "base.html" %}
{% block content %}
<script type="text/javascript" src="/media/js/admin/RelatedObjectLookups.js"></script> 
<script language="JavaScript">
	jQuery(document).ready(function(){
		$("#create-project-button").button();
		// ADD CSS TO BUTTONS
	    $('#actions').hover(function(){
	        $(this).removeClass('ui-state-default').addClass('ui-state-focus');
	    }, function(){
	        $(this).removeClass('ui-state-focus').addClass('ui-state-default');
	    });
	});
</script>
<h2>View projects</h2>
<table>
	<thead>
		<td>Name</td>
		<td>Description</td>
		<td>Create time</td>
		<td>Target</td>
		<td>Schedule</td>
		<td>Actions</td>
	</thead>
	{% for project in projects %}
	<tr>
		<td>{{ project.name }}</td>
		<td>{{ project.description }}</td>
		<td>{{ project.create_time|date:"SHORT_DATE_FORMAT" }}</td>
		<td>{{ project.target }}</td>
		<td>{{ project.schedule }}</td>
		<td class="ui-widget-header ui-corner-all ui-helper-clearfix">
			<a href="/project/launch/{{ project.id }}" title="Launch" class="ui-icon ui-icon-power" style="display: inline-table;"/>
			<a href="/project/configure/{{ project.id }}" title="Configure" class="ui-icon ui-icon-wrench" style="display: inline-table;"/>
			<a href="/project/result/{{ project.id }}" title="View results" class="ui-icon ui-icon-image" style="display: inline-table;"/>
			<a href="/project/delete/{{ project.id }}" title="Delete" class="ui-icon ui-icon-trash" style="display: inline-table;"/>
		</td>
	</tr>
	{% endfor %}
</table>
{% endblock %}

templates/project/view_results.html
{% extends "base.html" %}
{% block content %}
<h2>View results for project: <i>{{ my_project }}</i></h2>
<table>
	<thead>
		<td>ID</td>
		<td>Status</td>
		<td>Actions</td>
	</thead>
	{% for result in result_list %}
	<tr>
		<td>{{ result.id }}</td>
		<td>{{ result.get_state_display }}</td>
		<td class="ui-widget-header ui-corner-all ui-helper-clearfix">
			<a href="/project/result/{{ my_project.id }}/{{ result.id }}" title="View result" class="ui-icon ui-icon-image" style="display: inline-table;"/>
			<a href="#" title="Send report by email" class="ui-icon ui-icon-mail-closed" style="display: inline-table;"/>
			<a href="#" title="Generate report" class="ui-icon ui-icon-script" style="display: inline-table;"/>
		</td>
	</tr>
	{% endfor %}
</table>
{% endblock %}

templates/project/view_single_result.html
{% extends "base.html" %}
{% block content %}
<script type="text/javascript" src="http://www.google.com/jsapi"></script>
<script type="text/javascript" src="/js/jquery.gvChart-1.0.1.min.js"></script>
<script type="text/javascript">
	gvChartInit();
</script>
<script language="JavaScript">
	jQuery(document).ready(function(){				
		$("#report tr:odd").addClass("odd");
        $("#report tr:not(.odd)").hide();
        $("#report tr:first-child").show();     
        $("#report tr.odd").click(function(){
			$(this).next("tr").toggle();
            $(this).find("#arrow").toggleClass('ui-icon-triangle-1-s');
        });
		
		// Add tabs for each host
		$( "#tabs" ).tabs({
			ajaxOptions: {
				error: function( xhr, status, index, anchor ) {
					$( anchor.hash ).html( "Couldn't load this tab. We'll try to fix this as soon as possible. " );
				}
			}
		}).find( ".ui-tabs-nav" ).sortable({ axis: "x" });		
		
		// Create pie chart for total of vulnerabilities
		$("#vulns_table").gvChart({
			chartType: 'PieChart',
			gvSettings: {
				width: 500, height: 400,
	            is3D: true,
				colors: ['red', 'orange', 'yellow', 'green', 'blue', 'purple'],
				chartArea: {left:20,top:50,width:"100%",height:"70%"},
				backgroundColor: 'black',
				legendTextStyle: {color: 'white'},
				titleTextStyle: {color: 'white', fontSize: 14},
			}
		});
		
		// Create a column ba chart for vulns/host
		$("#vulns_host_table").gvChart({
			chartType: 'ColumnChart',
			gvSettings: {
	            width:600, height:400,
				backgroundColor: 'black',
				colors: ['red', 'orange', 'yellow', 'green', 'blue', 'purple'],
				chartArea: {left:20,top:50,width:"80%",height:"70%"},
				legendTextStyle: {color: 'white'},
				titleTextStyle: {color: 'white', fontSize: 14},
				hAxis: {slantedText:false, slantedTextAngle:45, textStyle: {color: 'white'} },
			}
		});
	});
</script>
<h2>Scan result for project: <i>{{ my_project.name }}</i></h2>
{% if finish %}
	<br/>
	<div id="executive_summary">
		<table>
			<tr>
				<td class="tdchart">
					<table id="vulns_table">
						<caption>Total vulnerabilities discovered</caption>
						<thead>
							<tr>
								<th></th>
								<th>Critical</th>
								<th>High</th>
								<th>Medium</th>
								<th>Low</th>
								<th>None</th>
								<th>Unknown</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<th></th>
								<td>2</td>
								<td>3</td>
								<td>7</td>
								<td>12</td>
								<td>8</td>
								<td>1</td>
							</tr>
						</tbody>
					</table>
				</td>
				<td class="tdchart">
					<table id="vulns_host_table">
						<caption>Number of vulnerabilities by host</caption>
						<thead>
							<tr>
								<th>#</th>
								<th>192.168.103.11</th>
								<th>192.168.103.12</th>
								<th>192.168.103.102</th>
								<th>192.168.103.103</th>
								<th>192.168.103.1</th>
								<th>192.168.103.2</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<th>Critical</th>
								<td>2</td>
								<td>1</td>
								<td>1</td>
								<td>0</td>
								<td>0</td>
								<td>3</td>
							</tr>
							<tr>
								<th>High</th>
								<td>2</td>
								<td>3</td>
								<td>1</td>
								<td>0</td>
								<td>2</td>
								<td>0</td>
							</tr>
							<tr>
								<th>Medium</th>
								<td>6</td>
								<td>4</td>
								<td>2</td>
								<td>7</td>
								<td>1</td>
								<td>3</td>
							</tr>
							<tr>
								<th>Low</th>
								<td>10</td>
								<td>9</td>
								<td>6</td>
								<td>11</td>
								<td>6</td>
								<td>3</td>
							</tr>
							<tr>
								<th>None</th>
								<td>5</td>
								<td>2</td>
								<td>3</td>
								<td>1</td>
								<td>4</td>
								<td>3</td>
							</tr>
							<tr>
								<th>Unknown</th>
								<td>8</td>
								<td>7</td>
								<td>4</td>
								<td>0</td>
								<td>3</td>
								<td>2</td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
		</table>
		<div id="tabs">
			<ul>
				<li><a href="#tabs-1">{{ my_project.target}}<a/></li>
				<li><a href="#tabs-2">{{ my_project.target}}<a/></li>
				<li><a href="#tabs-3">{{ my_project.target}}<a/></li>
				<li><a href="#tabs-4">{{ my_project.target}}<a/></li>
			</ul>
			<div id="tabs-1">
				<br/><br/>
				<div id="result">
					<table id="report">
						<tr>
							<th></th>
							<th>Title</th>
							<th>Summary</th>
							<th>Service</th>
							<th>Risk factor</th>
						</tr>
						{% for result in results %}
						<tr>
							<td><span id="arrow" class="ui-icon ui-icon-triangle-1-e"></span></td>
							<td>{{ result.title }}</td>
							<td>{{ result.summary }}</td>
							<td>{{ result.service }}</td>
							<td>{{ result.get_risk_factor_display }}</td>
						</tr>
						<tr>
							<td colspan="5" class="result-details">
								<h4><i>Description</i></h4>
								{{ result.description }}
								<ul>
				                    <li>NVT: <a href="http://www.openvas.org/?oid={{ result.nvt.oid }}">{{ result.nvt.oid }}</a></li>
				                    <li>CVE: <a href="http://cve.mitre.org/cgi-bin/cvename.cgi?name={{ result.cve }}">{{ result.cve }}</a></li>
				                    <li>BID: <a href="http://www.securityfocus.com/bid/{{ result.bid }}">{{ result.bid }}</a></li>
				                 </ul>  
							</td>
						</tr>
						{% endfor %}
					</table>
				</div>
			</div>
			<div id="tabs-2">test2</div>
			<div id="tabs-3">test3</div>
			<div id="tabs-4">test4</div>
		</div>
	</div>
	<br/><br/>
{% else %}
	The scan has not finished yet, please come back later!
{% endif %}
{% endblock %}